#!/bin/bash
# /etc/init.d/floppitAlarm

### BEGIN INIT INFO
# Provides:          floppitAlarm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Florence SG alarm
# Description:       Alarm and web app to monitor and control Florence's SG monitoring alarm
### END INIT INFO


case "$1" in 
    start)
        echo "Starting Floppit Alarm"
        /home/pi/start.sh
        ;;
    stop)
        echo "Stopping Floppit Alarm"
        /home/pi/stop.sh
        ;;
    *)
        echo "Usage: /etc/init.d/floppitAlarm start|stop"
        exit 1
        ;;
esac

exit 0
